version: "3"

services:
  sut:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        - GOARCH=arm64
        - GOARM=
    volumes:
      - ./tests/run-tests.sh:/run-tests.sh
    command: /run-tests.sh
